language: go
go:
  - 1.11.x
  - master
env:
  - GO111MODULES=on

before_install:
  - go get

script:
  - GOOS=linux GOARCH=amd64 go build
  - ls -al

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master