language: go
go:
  - 1.11.x
env:
  - GO111MODULES=on
addons:
  ssh_known_hosts: plex.hnxlabs.com:4430

before_install:
  - go get

script:
  - GOOS=linux GOARCH=amd64 go build
  - ls -al

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master