language: go
go:
  - 1.11.x
  - master
env:
  - GO111MODULES=on

before_install:
  - go get

script:
  - GOOS=linux GOARCH=amd64 go build
  - ls -al

deploy:
  provider: script
  script:
    - echo $SSH_PRIVATE_KEY > priv.key
    - chmod 400 priv.key
    - scp -i priv.key -P 4430 go-myubuntu abrar@plex.hnxlabs.com:~/bin/
  on:
    branch: master