language: go
go:
  - 1.11.x
  - master
env:
  - GO111MODULES=on

before_install:
  - go get

script:
  - GOOS=linux GOARCH=amd64 go build
  - ls -al

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RL_TOKEN
  file: "go-myubuntu"
  skip_cleanup: true
  overwrite: true